// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TenantService.Persistance.Context;

#nullable disable

namespace TenantService.Persistance.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20230606090556_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TenantService.Domain.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedTime");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedTime");

                    b.Property<int?>("EditionId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmailAddress");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<DateTime?>("SubscriptionEndDay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SubscriptionStartDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tenants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2023, 6, 6, 12, 5, 56, 184, DateTimeKind.Local).AddTicks(2233),
                            EditionId = 1,
                            EmailAddress = "admin@outlook.com",
                            IsDeleted = false,
                            Name = "admin",
                            SubscriptionEndDay = new DateTime(2023, 6, 6, 12, 5, 56, 184, DateTimeKind.Local).AddTicks(2209),
                            SubscriptionStartDay = new DateTime(2023, 6, 16, 12, 5, 56, 184, DateTimeKind.Local).AddTicks(2227),
                            Surname = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2023, 6, 6, 12, 5, 56, 184, DateTimeKind.Local).AddTicks(2250),
                            EditionId = 2,
                            EmailAddress = "default@outlook.com",
                            IsDeleted = false,
                            Name = "default",
                            SubscriptionEndDay = new DateTime(2023, 6, 6, 12, 5, 56, 184, DateTimeKind.Local).AddTicks(2248),
                            SubscriptionStartDay = new DateTime(2023, 6, 16, 12, 5, 56, 184, DateTimeKind.Local).AddTicks(2249),
                            Surname = "default"
                        },
                        new
                        {
                            Id = 3,
                            CreatedTime = new DateTime(2023, 6, 6, 12, 5, 56, 184, DateTimeKind.Local).AddTicks(2253),
                            EditionId = 1,
                            EmailAddress = "default@outlook.com",
                            IsDeleted = false,
                            Name = "bora",
                            SubscriptionEndDay = new DateTime(2023, 6, 6, 12, 5, 56, 184, DateTimeKind.Local).AddTicks(2251),
                            SubscriptionStartDay = new DateTime(2023, 6, 16, 12, 5, 56, 184, DateTimeKind.Local).AddTicks(2252),
                            Surname = "cetin"
                        },
                        new
                        {
                            Id = 4,
                            CreatedTime = new DateTime(2023, 6, 6, 12, 5, 56, 184, DateTimeKind.Local).AddTicks(2255),
                            EditionId = 3,
                            EmailAddress = "pinar@outlook.com",
                            IsDeleted = true,
                            Name = "pinar",
                            SubscriptionEndDay = new DateTime(2023, 6, 6, 12, 5, 56, 184, DateTimeKind.Local).AddTicks(2254),
                            SubscriptionStartDay = new DateTime(2023, 6, 26, 12, 5, 56, 184, DateTimeKind.Local).AddTicks(2255),
                            Surname = "uyar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
