// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TenantService.Persistance.Context;

#nullable disable

namespace TenantService.Persistance.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20230529084339_AddAuditEntity")]
    partial class AddAuditEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TenantService.Domain.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedTime");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedTime");

                    b.Property<int>("EditionId")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmailAddress");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<DateTime>("SubscriptionEndDay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SubscriptionStartDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tenants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EditionId = 1,
                            EmailAddress = "admin@outlook.com",
                            IsDeleted = false,
                            Name = "admin",
                            SubscriptionEndDay = new DateTime(2023, 5, 29, 11, 43, 39, 739, DateTimeKind.Local).AddTicks(382),
                            SubscriptionStartDay = new DateTime(2023, 6, 8, 11, 43, 39, 739, DateTimeKind.Local).AddTicks(397),
                            Surname = "admin"
                        },
                        new
                        {
                            Id = 2,
                            EditionId = 1,
                            EmailAddress = "default@outlook.com",
                            IsDeleted = false,
                            Name = "bora",
                            SubscriptionEndDay = new DateTime(2023, 5, 29, 11, 43, 39, 739, DateTimeKind.Local).AddTicks(412),
                            SubscriptionStartDay = new DateTime(2023, 6, 8, 11, 43, 39, 739, DateTimeKind.Local).AddTicks(412),
                            Surname = "cetin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
